In [14]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage import measure

In [21]:
def ExtractObjects(image):
    img=np.copy(image)
    blob_labels=measure.label(img,background=0)
    number_of_objects=np.unique(blob_labels)
    return blob_labels,number_of_objects

In [58]:
blob_labels.max()

5

In [59]:
number_of_objects

array([0, 1, 2, 3, 4, 5])

In [30]:
mask = cv2.imread("/content/Dove_men_acrylates_copolymer_microbeads_012(1).png", cv2.IMREAD_GRAYSCALE)
mask[mask!=255]=0
mask[mask==255]=1


In [31]:
mask.shape

(512, 512)

In [32]:
blob_labels,number_of_objects = ExtractObjects(mask)

In [33]:
blob_labels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
number_of_objects

array([0, 1, 2, 3, 4, 5])

In [35]:
len(number_of_objects)

6

In [60]:
labels = measure.label(mask)
regions = measure.regionprops(labels)
labels = [(r.area, r.label) for r in regions]

In [43]:
labels

[(1, 1), (1, 2), (2, 3), (2, 4), (3, 5)]

In [44]:
c=0
for r in regions:
  if r.area > 100:
    c+=1

c

0

In [29]:
labels>3

[(1, 1), (1, 2), (2, 3), (2, 4), (3, 5)]

In [ ]:
y_pred = model.predict(x_val)
number = 123 #56 ,34
img = y_pred[number,:,:,:]

opened_img, number_of_objects, blob_labels = post_processing(img)
print("Number of Trees: {}".format(number_of_objects[-1]))